In [1]:
import numpy as np
import torch
torch.manual_seed(1)
print(torch.__version__)

1.8.1+cpu


# base Tenseor

In [2]:
x = torch.Tensor(2,2)
x

tensor([[1.1729e-42, 0.0000e+00],
        [1.4200e+38, 9.3467e-43]])

In [3]:
x.type(), x.size(), x.numel()

('torch.FloatTensor', torch.Size([2, 2]), 4)

In [4]:
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]]])

In [5]:
x2.size(), x2.type(), x2.numel()

(torch.Size([4, 3, 2, 1]), 'torch.FloatTensor', 24)


# Other methods make to Tensor

In [6]:
torch.zeros(4,4), torch.ones(4,4), torch.eye(4,4),torch.rand(4,4), torch.randn(4,4)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]),
 tensor([[0.7576, 0.2793, 0.4031, 0.7347],
         [0.0293, 0.7999, 0.3971, 0.7544],
         [0.5695, 0.4388, 0.6387, 0.5247],
         [0.6826, 0.3051, 0.4635, 0.4550]]),
 tensor([[-0.6970, -1.1608,  0.6995,  0.1991],
         [ 0.8657,  0.2444, -0.6629,  0.8073],
         [ 1.1017, -0.1759, -2.2456, -1.4465],
         [ 0.0612, -0.6177, -0.7981, -0.1316]]))

In [7]:
x3 = torch.arange(0, 3, step=0.3)
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [8]:
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [9]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [10]:
numpy_test = np.array([[5,6],[10,11]])
torch.from_numpy(numpy_test)

tensor([[ 5,  6],
        [10, 11]], dtype=torch.int32)


# Use to array function of Python make Tensor 

In [11]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
x4[0:2,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x4[1]

tensor([4., 5., 6.])

In [14]:
x4[0,:]

tensor([1., 2., 3.])

In [15]:
x4[0:1,:] = torch.Tensor([62,72,80])
x4

tensor([[62., 72., 80.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [16]:
x4[1] = torch.Tensor([200,78, 89])
x4

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])

In [17]:
x5 = torch.split(x4, split_size_or_sections=1,dim=0)
x5

(tensor([[62., 72., 80.]]),
 tensor([[200.,  78.,  89.]]),
 tensor([[7., 8., 9.]]))

In [18]:
torch.cat(x5, dim=1)

tensor([[ 62.,  72.,  80., 200.,  78.,  89.,   7.,   8.,   9.]])

In [19]:
torch.stack(x5, dim=1)

tensor([[[ 62.,  72.,  80.],
         [200.,  78.,  89.],
         [  7.,   8.,   9.]]])

In [20]:
x6 = torch.randn(3,3)

mask  = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]])

out = torch.masked_select(x6, mask)

x6, mask, out

C:\Users\rbrain_user\Documents\DT_COE_COE1\python_env\lib\site-packages\ipykernel_launcher.py:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1004.)
  """


(tensor([[-0.4212, -0.5107, -1.5727],
         [-0.1232,  3.5870, -1.8313],
         [ 1.5987, -1.2770,  0.3255]]),
 tensor([[1, 0, 0],
         [1, 1, 1],
         [0, 1, 0]], dtype=torch.uint8),
 tensor([-0.4212, -0.1232,  3.5870, -1.8313, -1.2770]))


# Reshaping on dimension of Tensor

In [21]:
x7 = torch.zeros(2,2,1)
x7

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [22]:
x7.view(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [23]:
x7.view(-1) # -1 = Automatic

tensor([0., 0., 0., 0.])

In [24]:
x7.view(-1,2)

tensor([[0., 0.],
        [0., 0.]])

In [25]:
x7.view(4)

tensor([0., 0., 0., 0.])

In [26]:
x8 = x7.squeeze()
x7, x8

(tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [27]:
x8.unsqueeze(0)

tensor([[[0., 0.],
         [0., 0.]]])


# Calculate

In [28]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
x9, x10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [29]:
x9  + x10, x9.add(x10), torch.add(x9, x10)

(tensor([[11., 22., 33.],
         [44., 55., 66.]]),
 tensor([[11., 22., 33.],
         [44., 55., 66.]]),
 tensor([[11., 22., 33.],
         [44., 55., 66.]]))

In [30]:
x10.sub(x9), x9.sub(x10)

(tensor([[ -9., -18., -27.],
         [-36., -45., -54.]]),
 tensor([[ 9., 18., 27.],
         [36., 45., 54.]]))

In [31]:
x10[1] + 12

tensor([16., 17., 18.])

In [32]:
x9 * x10, x10.mul(x9), torch.mul(x10,x9)

(tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]),
 tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]),
 tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]))

In [33]:
x10 * 10

tensor([[10., 20., 30.],
        [40., 50., 60.]])


# Other Calculate

In [34]:
x9.pow(2), torch.pow(x9,2), x9 ** 2

(tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]),
 tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]),
 tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]))

In [35]:
x9.sqrt()

tensor([[3.1623, 4.4721, 5.4772],
        [6.3246, 7.0711, 7.7460]])

In [36]:
x10.log(), torch.log(x10)

(tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]),
 tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

In [37]:
x9 % 3, x9 / 3

(tensor([[1., 2., 0.],
         [1., 2., 0.]]),
 tensor([[ 3.3333,  6.6667, 10.0000],
         [13.3333, 16.6667, 20.0000]]))

In [38]:
x9.sum(), x9.max()

(tensor(210.), tensor(60.))

In [39]:
x10.min(), x10.min(0), x10.min(1)

(tensor(1.),
 torch.return_types.min(
 values=tensor([1., 2., 3.]),
 indices=tensor([0, 0, 0])),
 torch.return_types.min(
 values=tensor([1., 4.]),
 indices=tensor([0, 0])))

In [40]:
x10.max(1)

torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

In [41]:
x9.abs(), x9

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [42]:
x9[1] = torch.Tensor([-3,3,-10])
x9, x9.abs()

(tensor([[ 10.,  20.,  30.],
         [ -3.,   3., -10.]]),
 tensor([[10., 20., 30.],
         [ 3.,  3., 10.]]))

In [43]:
value, index = x10.max(dim = 1)
value, index

(tensor([3., 6.]), tensor([2, 2]))

In [44]:
x10.max()

tensor(6.)


# Matrix Calculate

In [ ]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13

In [ ]:
1.6200 * 1.1375  + 0.3436 * -0.9347 + -0.9112 * 1.3267 + -0.9952 *  -0.0336 + 0.7455 * 1.3210

In [ ]:
torch.mm(x11,x12), x11.mm(x12)

In [ ]:
x11.mm(x12).mm(x13)

In [ ]:
x11.mm(x12).mm(x13).mm(x11)

In [ ]:
x14 = torch.randn(3, 4)
v = torch.randn(4)

x14, v

In [ ]:
 -0.4594 * 0.6623 + -1.1798 * 0.2916 +0.3812 * 0.0409+ -0.0064 *  -1.1908

In [ ]:
torch.mv(x14,v), x14.mv(v)

In [ ]:
x15 = torch.randn(10,3,4)
x16 = torch.randn(10,4,5)

torch.bmm(x15, x16).size()

In [ ]:
torch.bmm(x15, x16)

In [ ]:
x17 = torch.randn(2,2)
x18 = torch.randn(2,2)

torch.dot(x17.view(-1), x18.view(-1)), x17, x18

In [ ]:
1.7038 *  -0.6295 + -1.6000 *  -1.0304 +  1.4366 * -0.0231 + -0.9917 * 0.1807

In [ ]:
torch.dot(x17.view(-1), x18.view(-1))

In [ ]:
x19  = torch.rand(3,4)

x19, x19.t()

In [ ]:
u, s, v = torch.svd(x19)
u, s, v, x19

In [ ]:
torch.dist(x19, torch.mm(torch.mm(u, torch.diag(s)), v.t()))


# Tensor Data Type

In [ ]:
x20 = torch.rand(2,2)
x20

In [ ]:
x20  = torch.LongTensor([1,1])
x20

In [ ]:
x20.float()

In [ ]:
x20.double()

In [ ]:
x20.byte()

In [ ]:
x20

In [ ]:
x20 = x20.cpu()
x20

In [ ]:
x20.numpy()

In [ ]:
torch.from_numpy(np.random.rand(3,2))